

// var language; 
// function getLanguage() {
// (localStorage.getItem('language') == null) ? setLanguage('ar') : false;
// $.ajax({ 
// url:  '/language/' +  localStorage.getItem('language') + '.json', 
// dataType: 'json', async: false, dataType: 'json', 
// success: function (lang) { language = lang } });
// alert("hello")
// }

// function setLanguage(lang) {
// localStorage.setItem('language', lang);
// alert("HELLO")
// }

// $(document).ready(function(){
//     $('#termLabel').text(language.termLabel);
//     });
    

// function changeLanguage(lang) {
//     location.hash = lang;
//     location.reload();
//     console.log("hello")
//     alert("Help!");
//     console.log("Help me!");
//   }

  // Define the language reload anchors
  // var language = {
  //   en: {
        
  //           "termLabel":"Date of agreement ",
  //           "termContent":"The last update to our agreement was on 29/4/2023 .",
  //           "termLabel1":"Terms and conditions for the Best Gas Carrier application.",
  //           "termContent1":"The Best Gas Carrier application management has set these terms and conditions to inform customers of what they must do when they use our electronic application, because violating our terms and conditions or any of them may cause the ban or suspension of the violating customer's account.",
  //           "termLabel2":"The introduction",
  //           "termConent2":"We kindly ask customers to know that they must agree to our current terms or conditions that we have the right to add in the future, because if a customer does not agree to our terms or conditions or any of them, then in this case he will not be entitled to use our application or deal with it, but he must immediately exit from our application and not to use it until he agrees to all our terms and conditions",
  //           "termLabel3":"Conditions for registering with the Best Gas Carrier application.",
  //           "termConent3":"1 - All customers are obligated to provide us with all the data we need from them (full name, e-mail, phone number, and username) and this data must be true and accurate so that the customer can use our application and the customer must review his personal data before providing us with this data. 2 - The age of the customer wishing to register with our application must be at least 18 years old in order to be able to use our application, deal with it, and purchase from it, and those under 18 years old can use our application, if their parents agree to deal with us.3 - The customer is obligated to allow the best gas carrier application to know his location, that is, the place he lives, so that we can provide our service to him. 4 - The customer is obligated to provide us with an activated payment method so that he can deal with the application and purchase from the various products in it",
  //           "termLabel4":"Conditions for dealing with the application of the best gas carrier",
  //           "termContent4":"All customers are obligated to use our application in a manner that is consistent with the laws and that our electronic application does not cause any damage, and all customers must be committed to the necessity of using our application in a manner that is consistent with Islamic law. 2 - The customer, when using our application, is obligated not to do any abuse of our application, do any abuse to any other user, or do any abuse to the service supplier, because whoever does any abuse or commits any violation of any of our rights, we will ban this user from using our application with our entitlement To take all legal measures to punish those who committed this offense or committed this violation.4 - Our application has the right to accept or reject any purchase request for any customer without the need to give any reasons for their doing so. 5 - It is completely forbidden to use the Better Gas Carrier application for any commercial or advertising purposes without obtaining prior approval from the site and application management. 6 - Dealing with our application is the responsibility of the customer alone, so that the customer uses our application in a way that does not cause him any damage. 7 - The customer is obligated to pay compensation to the Best Gas Carrier application in the event that it violates its terms, or if the customer causes damage to an application while using it, or if it violates any law, and this causes the Best Gas Carrier application to pay those compensations",
  //           "termLabel5":"inquiries",
  //           "termContent5":"1 - Our staff is fully prepared to answer any question or inquiry you may ask them, and our staff is ready to help you understand anything ambiguous for you. 2 - If you encounter any problem while using our electronic application, you should immediately contact our technical support so that they solve your problem with your full commitment to the friendly solutions they provide you.",
  //           "termLabel6":"Modifications, changes, additions and updates that may be made to this Agreement.",
  //           "termContent6":"We seek to continuously develop the application of the best gas carrier in order to meet all the aspirations of customers, so the application management requests that the customers need to follow this policy constantly to get acquainted with any amendments, changes, additions or improvements that we have implemented to this agreement, because as soon as we implement any new item or We have amended any clause in this agreement, as it will be applied to all customers",
  //           "termLabel7":"General conditions for the application of the Best Gas Carrier.",
  //           "termContent7":"1 - The customer is obligated to use our application in a legal manner that does not cause us any damages of any kind or make us pay any compensation for any reason. 2 - Customers are obligated not to do anything that violates the laws or violates the regulations, laws and rules of the Kingdom of Saudi Arabia while using our application and our website. 3 - The customer is committed to all our terms and conditions, and the customer must not violate any of our rights, because any user who does so, we will immediately ban him from using our application, while taking appropriate legal measures to punish him for what he has done. 4 - The customer can follow our exclusive offers and our latest news on the various social networking pages they are on.5 - The customer is obligated to provide the Better Gas Carrier application with correct and accurate data so that he can create a new account for himself and so that the customer can use our application and deal with it. 6 - The customer acknowledges that he has read all the terms and conditions mentioned in this agreement, and the customer is obligated to acknowledge that he will agree to all the terms and conditions that the application management may add to this agreement in the future",
  //           "termLabel8":"Limits of our responsibility  ",
  //           "termContent8":"The customer registers an account in the application so that he can purchase from the various products in the application. The limits of our responsibility are represented in preserving the rights of the customer, and the customer purchases these products through the application or from the self-service units and through the payment methods provided by the application, and after that the products that the customer purchased are received from the service units Their locations are specified through the application",
  //           "termLabel9":"Evacuation responsibilaty",
  //           "termContent9": "1 - The management of the Better Gas Carrier application disclaims its full responsibility in the event that the customer provides us with wrong data, and this results in any kind of damage to him, such as the customer providing us with wrong data about his address, and the customer’s purchases were delivered to this wrong address. 2 - We disclaim our full responsibility in the event that the customer uses or misuses our website or our electronic application, which results in direct or indirect harm to this customer ... 6 - The customer is fully responsible for the personal data that he provides to us or for the opinions he mentions or for The files that he uploads and there is no responsibility on the application of the best gas carrier for these matters.",
  //           "termLabel10":"Privacy policy for the application and site of the best gas carrier",
  //           "termContent10":"Make sure that maintaining the privacy of your personal data that you provide us with is one of our main priorities. Therefore, we ask you to read this policy carefully and agree to the terms mentioned in it in order to be able to use our application and our website. This policy includes many items such as the data we need from you, how we protect Your personal data, customer rights, application rights and other important items. The privacy policy for the Best Gas Carrier application and site contains the following items: - The data that the Best Gas Carrier website and application needs from customers:1 - The Best Gas Carrier application needs some important data when the customer announces his desire to create a new account for him in the application, and the data that we need from him in this case is such as the first name, last name, email, phone number, full name, entering a password to maintain your personal account, and approval On the privacy policy, terms and conditions for the Best Gas Carrier application, and any other data requested by the Best Gas Carrier website, the customer is fully obligated to provide us with that data.2 - The Best Gas Carrier application requests some important and necessary data to complete the payment process, when the customer purchases from the various products in our application, and the data that we need in this case is such as the bank card number that the customer wishes to pay through, the expiration date of this card, the verification code For this card, and any other data required by the Better Gas Carrier application to complete the payment process, the customer is fully obligated to provide us with that data. 4 - The application of the best gas carrier needs some important data when the customer announces his desire to communicate with us so that we can answer him about anything vague to him.5- The Better Gas Carrier application requests some data from the customer about the location of the house in order to show him the nearest available machinery locations so that we provide the customer with the products he needs from our application. 6 - The best gas carrier application asks the customer to agree to the application obtaining his location (i.e. the place where he lives) and we also require some data about the customer’s residence address",
  //           "termLabel11":"Intellectual rights and copyrights for the application of the best gas carrier",
  //           "termContent11":" We have created a distinctive brand that defines customers with the great services that we offer them. Therefore, it is completely forbidden for any party or individual to use our trademark except after obtaining a written and signed approval from the management of the Better Gas Carrier website and application so that they can use our trademark. 2 - The Best Gas Carrier website contains many types of content that are wholly owned by the management of the application, so it is strictly forbidden for any application, any site, or any party, regardless of its authority, to copy, paste, or use any of our content, because any person or party By doing so, our legal team will take urgent legal action against those who have violated any of our rights.3 - It is forbidden for any party or person to put, upload or publish any viruses or harmful links to our application or our website, and any person or entity that does any of these matters, we will take urgent legal measures against whoever does any of these prohibited things Do it with our app and website. 4 - While using our application, you undertake to use our application in a fair manner that does not cause us any damage, and you must also undertake that you will not violate our rights or attempt to violate any of our rights because whoever does any of these matters, the management of the site and application of the best gas carrier will take legal measures Urgent to punish whoever did it "
            
        
  //   },
  //   ar: {
  //       "termLabel":"تاريخ الاتفاقية",
  //       "termContent":"آخر تحديث تم القيام به للإتفاقية الخاصة بنا كان بتاريخ 29/04/2023م.",
  //       "termLabel1":"الشروط والأحكام الخاصة بتطبيق الناقل الأفضل للغاز  ",
  //       "termContent1":"قامت إدارة تطبيق الناقل الافضل للغاز بوضع هذه الشروط والأحكام لتعريف العملاء بما يجب عليهم القيام به عند استخدامهم لتطبيقنا الإليكتروني, لأن مخالفة شروطنا وأحكامنا أو أحدًا منها من الممكن أن يتسبب ذلك في حظر أو إيقاف حساب العميل المخالف.",
  //       "termLabel2":"المقدمة",
  //       "termConent2":"نرجو من السادة العملاء العلم بأنه يجب عليهم الموافقة على شروطنا الحالية أو الشروط التي يحق لنا إضافتها بالمستقبل ألنه في حالة عدم موافقة أحد العملاء على شروطنا أو أحكامنا أو أحدًا منهم ففي هذه الحالة لن يحق له استخدام تطبيقنا أو التعامل معه بل يجب عليه على الفور الخروج من تطبيقنا وألا يقوم باستخدامه حتى يوافق على كافة شروطنا وأحكامنا    </div>",
  //       "termLabel3":" شروط التسجيل بتطبيق الناقل الافضل للغاز",
  //       "termConent3":"1 -يلتزم كافة العملاء بتزويدنا بكافة البيانات التي نحتاجها منهم (الإسم بالكامل والبريد الإليكتروني, رقم الهاتف, واسم المستخدم)كما يجب أن تكون هذه البيانات صحيحة ودقيقة حتى يتمكن العميل من استخدام تطبيقنا كما يجب على العميل مراجعة بياناته الشخصية قبل تزويدنا بهذه البيانات. 2 -يجب أن يكون عمر العميل الراغب بالتسجيل بتطبيقنا هو 18 عام على الأقل حتى يتمكن من استخدام تطبيقنا والتعامل معه والشراء منه, كما يمكن لمن هم دون 18 عام استخدام تطبيقنا وذلك في حال موافقة والديهم على قيامهم بالتعامل معنا. 3 -يلتزم العميل بالسماح لتطبيق الناقل الافضل للغاز بمعرفة موقعه أي المكان الذي يعيش حتى نتمكن من تقديم خدمتنا إليه. 4 -يلتزم العميل بتزويدنا بوسيلة دفع مفعلة حتى يتمكن من التعامل مع التطبيق والشراء من المنتجات المتنوعة الموجودة فيه",
  //       "termLabel4":"شروط التعامل مع تطبيق الناقل الافضل للغاز",
  //       "termContent4":"يلتزم كافة العملاء بضرورة استخدام تطبيقنا بشكل يتوافق مع القوانين ولا يسبب لتطبيقنا الإلكتروني أية أضرار,كما يجب أن يلتزم كافة العملاء بضرورة استخدام تطبيقنا بشكل يتوافق مع الشريعة الإسلامية. 2 - يلتزم العميل عند استخدامه لتطبيقنا بألا يقوم بفعل أي إساءة لتطبيقنا أو فعل أي إساءة لأي مستخدم آخر أو فعل أي إساءة لمورد الخدمة لأن من يقوم بفعل إي إساءة أو يقوم بفعل أي انتهاك أي من حقوقنا فأننا سنقوم بحظر هذا المستخدم من استخدام تطبيقنا مع إحقيتنا في إتخاذ كافة الإجراءات القانونية لمعاقبة من قام بفعل هذه الإساءة أو قام بفعل هذا الانتهاك.. 4 - يحق لتطبيقنا قبول أو رفض أي طلب شراء خاص بأي عميل دون الحاجة إلى إبداء أية أسباب لقيامهم بفعل ذلك. 5 - يمنع بشكل كامل أن يتم استخدام تطبيق الناقل الافضل للغاز لأية أغراض تجارية أو أية أغراض إعلانية دون الحصول على موافقة مسبقة من قبل إدارة الموقع والتطبيق. 6 - التعامل مع تطبيقنا يكون واقع على مسؤولية العميل وحده بحيث يستخدم العميل تطبيقنا بشكل لا يسبب له أية أضرار. 7 - يلتزم العميل بتحمل دفع تعويضات لتطبيق الناقل الافضل للغاز في حالة مخالفته لشروطه أو في حال تسبب العميل بضرر لتطبيق أثناء استخدامه له أو في حال انتهاكه لأي قانون وتسبب ذلك في جعل تطبيق الناقل الافضل للغاز يدفع تلك التعويضات",
  //       "termLabel5":"الاستفسارات",
  //       "termContent5":"1 - موظفينا على أتم الاستعداد للإجابة على أي سؤال أو استفسار تطرحه عليهم, كما أن موظفينا مستعدين لمساعدتك في فهم أي شيء غامض بالنسبة لك. 2 - إذا واجهت أي مشكلة أثناء استخدامك لتطبيقنا الإلكتروني فعليك على الفور التواصل مع الدعم الفني الخاص بنا حتى يقوموا بحل مشكلتك مع إلتزامك بشكل كامل بالحلول الودية التي يقدمونها لك",
  //       "termLabel6":"التعديلات والتغييرات والإضافات والتحديثات التي يمكن إجراؤها لهذه الاتفاقية",
  //       "termContent6":"نسعى إلى تطوير تطبيق الناقل الافضل للغاز بشكل مستمر حتى يلبي كافة تطلعات العملاء, لذلك ترجو إدارة التطبيق من السادة العملاء ضرورة متابعة هذه السياسة باستمرار للتعرف على أي تعديلات أو تغييرات أو إضافات أو تحسينات قمنا بتنفيذها لهذه الاتفاقية, لأنه بمجرد قيامنا بتنفيذ أي بند جديد أو قمنا بتعديل أي بند موجود في هذه الاتفاقية فأنه سيكون مطبق على كافة العملاء ",
  //       "termLabel7":"شروط عامة خاصة بتطبيق الناقل الافضل للغاز",
  //       "termContent7":"1 - يلتزم العميل باستخدام تطبيقنا بشكل قانوني لا يسبب لنا أية أضرار من أي نوع أو يجعلنا نقوم بدفع أية تعويضات لأي سبب كان. 2 - يلتزم العملاء بعدم فعل أي شيء ينتهك القوانين أو ينتهك الأنظمة والقوانين والقواعد الخاصة بالمملكة العربية السعودية أثناء استخدامه لتطبيقنا وموقعنا الإلكتروني. 3 - يلتزم العميل بكافة شروطنا وأحكامنا ويجب ألا يقوم العميل بإنتهاك أي من حقوقنا لأن أي مستخدم يقوم بفعل ذلك فأننا سنقوم على الفور بحظره من استخدام تطبيقنا مع إتخاذ الإجراءات القانونية المناسبة لمعاقبته على ما قام بفعله. 4 - يمكن للعميل متابعة عروضنا الحصرية وأخر أخبارنا على صفحات التواصل الاجتماعي المختلفة الموجودين عليها. 5 - يلتزم العميل بتزويد تطبيق الناقل الافضل للغاز ببيانات صحيحة ودقيقة حتى يتمكن من إنشاء حساب جديد خاص به وحتى يتمكن العميل من استخدام تطبيقنا والتعامل معه. 6 - يقر العميل بأنه قرأ كافة الشروط والأحكام المذكورة في هذه الاتفاقية, كما يلتزم العميل بأن يقر بأن سيوافق على كافة الشروط والأحكام التي من المحتمل أن تضيفها إدارة التطبيق إلى هذه الاتفاقية بالمستقبل",
  //       "termLabel8":"حدود مسؤوليتنا ",
  //       "termContent8":"يقوم العميل بتسجيل حساب بالتطبيق حتى يتمكن من الشراء من المنتجات المتنوعة بالتطبيق فحدود مسؤوليتنا متمثلة في المحافظة على حقوق العميل ويشتري العميل تلك المنتجات عبر التطبيق او من وحدات الخدمة الذاتية ومن خلال وسائل الدفع التي يوفرها التطبيق وبعد ذلك يتم استلام المنتجات التي اشتراها العميل من وحدات الخدمة و المحدد مواقعها من خلال التطبيق",
  //       "termLabel9":"إخلاء المسؤولية  ",
  //       "termContent9":"1 - تخلي إدارة تطبيق الناقل الافضل للغاز مسؤوليتها الكاملة وذلك في حال قيام العميل بتزويدنا ببيانات خاطئة ونتج عن ذلك أي نوع من الأضرار له مثل تزويد العميل لنا ببيانات خاطئة عن عنوانه وتم إيصال مشتريات العميل إلى هذا العنوان الخاطئ. 2 - نخلي مسؤوليتنا الكاملة وذلك في حال استخدام أو سوء استخدام العميل لموقعنا أو لتطبيقنا الإلكتروني ونتج عن ذلك ضرر مباشر أو ضرر غير مباشر لهذا العميل... 6 - العميل مسؤول بشكل كامل عن البيانات الشخصية التي يزودها لنا أو عن الآراء التي يذكرها أو عن الملفات التي يقوم بتحميلها ولا تقع أي مسؤولية على تطبيق الناقل الافضل للغاز عن هذه الأمور.",
  //       "termLabel10":"سياسة الخصوصية الخاصة بتطبيق وموقع الناقل الافضل للغاز",
  //       "termContent10":"تأكد أن المحافظة على خصوصية بياناتك الشخصية التي تزودنا بها هي أحد أولويتنا الرئيسية لذلك نرجو منك قراءة هذه السياسة بعناية والموافقة على ما ذكر فيها من بنود حتى تتمكن من استخدام تطبيقنا وموقعنا الإلكتروني, وتشمل هذه السياسة العديد من البنود مثل البيانات التي نحتاجها منك, كيف نحمي بياناتك الشخصية, حقوق العملاء , حقوق التطبيق وغيرها من البنود الهامة الأخرى, سياسة الخصوصية الخاصة بتطبيق وموقع الناقل الافضل للغاز تحتوي على البنود التالية:- البيانات التي يحتاجها موقع وتطبيق الناقل الافضل للغاز من العملاء -: 1 - يحتاج تطبيق الناقل الافضل للغاز بعض البيانات الهامة حين يقوم العميل بإعلان رغبته بإنشاء حساب جديد له بالتطبيق والبيانات التي نحتاجها منه في هذه الحالة تكون مثل الاسم الأول واسم العائلة والبريد الإلكتروني, رقم الهاتف, الاسم بالكامل وإدخال كلمة مرور للحفاظ على حسابك الشخصي, والموافقة على سياسة الخصوصية والشروط والأحكام الخاصة بتطبيق الناقل الافضل للغاز وأي بيانات أخرى يطلبها موقع الناقل الافضل للغاز يكون العميل ملزم بشكل كامل بتزويدنا بتلك البيانات. 2 - يطلب تطبيق الناقل الافضل للغاز بعض البيانات الهامة والضرورية لاكمال عملية الدفع وذلك حين يقوم العميل بالشراء من المنتجات المتنوعة الموجودة بتطبيقنا, والبيانات التي نحتاجها في هذه الحالة تكون مثل رقم البطاقة البنكية التي يرغب العميل بالدفع من خلالها, تاريخ إنتهاء هذه البطاقة, رمز التحقق الخاص بهذه البطاقة, وأي بيانات أخرى يطلبها تطبيق الناقل الافضل للغاز لاكمال عملية الدفع يكون العميل ملزم بشكل كامل بتزويدنا بتلك البيانات. 4 - يحتاج تطبيق الناقل الافضل للغاز بعض البيانات الهامة حين يقوم العميل بإعلان رغبته بالتواصل معنا حتى نجيب له عن أي شيء مبهم بالنسبة له. 5- يطلب تطبيق الناقل الافضل للغاز بعض البيانات من العميل حول مكان المنزل حتى يظهر له أقرب أماكن المكينات المتاحة حتى نزود العميل بالمنتجات التي يحتاجها من تطبيقنا. 6 - يطلب تطبيق الناقل الافضل للغاز من العميل الموافقة على حصول التطبيق على موقعه )أي المكان الذي يعيش فيه( كما نطلب بعض البيانات حول عنوان إقامة العميل",
  //       "termLabel11":" الحقوق الفكرية وحقوق النشر لتطبيق الناقل الافضل للغاز",
  //       "termContent11":"قمنا بإنشاء علامة تجارية مميزة تعرف العملاء بالخدمات العظيمة التي نقدمها لهم لذلك يمنع بشكل كامل أن تقوم أي جهة أو أي فرد باستخدام علامتنا التجارية إلا بعد الحصول على موافقة مكتوبة وموقعة من قبل إدارة موقع وتطبيق الناقل الافضل للغاز حتى يتمكنوا من استخدام علامتنا التجارية. 2 - يحتوي موقع الناقل الافضل للغاز على العديد من أنواع المحتوى المملوكة بشكل كامل لإدارة التطبيق لذلك يمنع بشكل تام أن يقوم أي تطبيق أو أي موقع أو أي جهة مهما كان سلطتها نسخ أو لصق أو استخدام أي محتوى خاص بنا, لأن أي شخص أو جهة يقوم بفعل ذلك سوف يتخذ الفريق القانوني الخاص بنا إجراءات قانونية عاجلة ضد من انتهك أي من حقوقنا. 3 - يمنع أن تقوم أي جهة أو أي شخص بوضع أو تحميل أو نشر أي فيروسات أو روابط ضارة بتطبيقنا أو بموقعنا الإلكتروني وأي شخص أو جهة يقوم بفعل أي شيء من تلك الأمور فأننا سنتخذ إجراءات قانونية عاجلة ضد من قام بفعل أي شيء من تلك الأمور المحظور فعلها بتطبيقنا وموقعنا الإلكتروني. 4 - أثناء استخدامك لتطبيقنا فأنك تتعهد باستخدام تطبيقنا بشكل عادل لا يسبب لنا أية أضرار, كما يجب أن تتعهد بأنك لن تقوم بإنتهاك حقوقنا أو بمحاولة إنتهاك أي من حقوقنا لأنه من يفعل أي شيء من هذه الأمور فإن إدارة موقع وتطبيق الناقل الافضل للغاز ستتخذ إجراءات قانونية عاجلة لمعاقبة من فعل ذلك"
        
  //   },
   
  // };

  // // Check if a hash value exists in the URL
  // if (window.location.hash) {

  //   // Set the content of the webpage 
  //   // depending on the hash value
  //   if (window.location.hash == "#en") {
  //       termLabel.textContent =
  //       language.en.welcome;
  //   }
   
  // }
//   $(document).ready(function() {
//     // The default language is English
//     var lang = "ar";
//     $(".lang").each(function(index, element) {
//       $(this).text(arrLang[lang][$(this).attr("key")]);
//     });
//   });
  
//   // get/set the selected language
//   $(".translate").click(function() {
//     var lang = $(this).attr("id");
  
//     $(".lang").each(function(index, element) {
//       $(this).text(arrLang[lang][$(this).attr("key")]);
//     });
//   });
//   var arrLang = {
//     "ar": {
//       "termLabel":"تاريخ الاتفاقية",
//       "termContent":"آخر تحديث تم القيام به للإتفاقية الخاصة بنا كان بتاريخ 29/04/2023م.",
//       "termLabel1":"الشروط والأحكام الخاصة بتطبيق الناقل الأفضل للغاز  ",
//       "termContent1":"قامت إدارة تطبيق الناقل الافضل للغاز بوضع هذه الشروط والأحكام لتعريف العملاء بما يجب عليهم القيام به عند استخدامهم لتطبيقنا الإليكتروني, لأن مخالفة شروطنا وأحكامنا أو أحدًا منها من الممكن أن يتسبب ذلك في حظر أو إيقاف حساب العميل المخالف.",
//       "termLabel2":"المقدمة",
//       "termConent2":"نرجو من السادة العملاء العلم بأنه يجب عليهم الموافقة على شروطنا الحالية أو الشروط التي يحق لنا إضافتها بالمستقبل ألنه في حالة عدم موافقة أحد العملاء على شروطنا أو أحكامنا أو أحدًا منهم ففي هذه الحالة لن يحق له استخدام تطبيقنا أو التعامل معه بل يجب عليه على الفور الخروج من تطبيقنا وألا يقوم باستخدامه حتى يوافق على كافة شروطنا وأحكامنا    </div>",
//       "termLabel3":" شروط التسجيل بتطبيق الناقل الافضل للغاز",
//       "termConent3":"1 -يلتزم كافة العملاء بتزويدنا بكافة البيانات التي نحتاجها منهم (الإسم بالكامل والبريد الإليكتروني, رقم الهاتف, واسم المستخدم)كما يجب أن تكون هذه البيانات صحيحة ودقيقة حتى يتمكن العميل من استخدام تطبيقنا كما يجب على العميل مراجعة بياناته الشخصية قبل تزويدنا بهذه البيانات. 2 -يجب أن يكون عمر العميل الراغب بالتسجيل بتطبيقنا هو 18 عام على الأقل حتى يتمكن من استخدام تطبيقنا والتعامل معه والشراء منه, كما يمكن لمن هم دون 18 عام استخدام تطبيقنا وذلك في حال موافقة والديهم على قيامهم بالتعامل معنا. 3 -يلتزم العميل بالسماح لتطبيق الناقل الافضل للغاز بمعرفة موقعه أي المكان الذي يعيش حتى نتمكن من تقديم خدمتنا إليه. 4 -يلتزم العميل بتزويدنا بوسيلة دفع مفعلة حتى يتمكن من التعامل مع التطبيق والشراء من المنتجات المتنوعة الموجودة فيه",
//       "termLabel4":"شروط التعامل مع تطبيق الناقل الافضل للغاز",
//       "termContent4":"يلتزم كافة العملاء بضرورة استخدام تطبيقنا بشكل يتوافق مع القوانين ولا يسبب لتطبيقنا الإلكتروني أية أضرار,كما يجب أن يلتزم كافة العملاء بضرورة استخدام تطبيقنا بشكل يتوافق مع الشريعة الإسلامية. 2 - يلتزم العميل عند استخدامه لتطبيقنا بألا يقوم بفعل أي إساءة لتطبيقنا أو فعل أي إساءة لأي مستخدم آخر أو فعل أي إساءة لمورد الخدمة لأن من يقوم بفعل إي إساءة أو يقوم بفعل أي انتهاك أي من حقوقنا فأننا سنقوم بحظر هذا المستخدم من استخدام تطبيقنا مع إحقيتنا في إتخاذ كافة الإجراءات القانونية لمعاقبة من قام بفعل هذه الإساءة أو قام بفعل هذا الانتهاك.. 4 - يحق لتطبيقنا قبول أو رفض أي طلب شراء خاص بأي عميل دون الحاجة إلى إبداء أية أسباب لقيامهم بفعل ذلك. 5 - يمنع بشكل كامل أن يتم استخدام تطبيق الناقل الافضل للغاز لأية أغراض تجارية أو أية أغراض إعلانية دون الحصول على موافقة مسبقة من قبل إدارة الموقع والتطبيق. 6 - التعامل مع تطبيقنا يكون واقع على مسؤولية العميل وحده بحيث يستخدم العميل تطبيقنا بشكل لا يسبب له أية أضرار. 7 - يلتزم العميل بتحمل دفع تعويضات لتطبيق الناقل الافضل للغاز في حالة مخالفته لشروطه أو في حال تسبب العميل بضرر لتطبيق أثناء استخدامه له أو في حال انتهاكه لأي قانون وتسبب ذلك في جعل تطبيق الناقل الافضل للغاز يدفع تلك التعويضات",
//       "termLabel5":"الاستفسارات",
//       "termContent5":"1 - موظفينا على أتم الاستعداد للإجابة على أي سؤال أو استفسار تطرحه عليهم, كما أن موظفينا مستعدين لمساعدتك في فهم أي شيء غامض بالنسبة لك. 2 - إذا واجهت أي مشكلة أثناء استخدامك لتطبيقنا الإلكتروني فعليك على الفور التواصل مع الدعم الفني الخاص بنا حتى يقوموا بحل مشكلتك مع إلتزامك بشكل كامل بالحلول الودية التي يقدمونها لك",
//       "termLabel6":"التعديلات والتغييرات والإضافات والتحديثات التي يمكن إجراؤها لهذه الاتفاقية",
//       "termContent6":"نسعى إلى تطوير تطبيق الناقل الافضل للغاز بشكل مستمر حتى يلبي كافة تطلعات العملاء, لذلك ترجو إدارة التطبيق من السادة العملاء ضرورة متابعة هذه السياسة باستمرار للتعرف على أي تعديلات أو تغييرات أو إضافات أو تحسينات قمنا بتنفيذها لهذه الاتفاقية, لأنه بمجرد قيامنا بتنفيذ أي بند جديد أو قمنا بتعديل أي بند موجود في هذه الاتفاقية فأنه سيكون مطبق على كافة العملاء ",
//       "termLabel7":"شروط عامة خاصة بتطبيق الناقل الافضل للغاز",
//       "termContent7":"1 - يلتزم العميل باستخدام تطبيقنا بشكل قانوني لا يسبب لنا أية أضرار من أي نوع أو يجعلنا نقوم بدفع أية تعويضات لأي سبب كان. 2 - يلتزم العملاء بعدم فعل أي شيء ينتهك القوانين أو ينتهك الأنظمة والقوانين والقواعد الخاصة بالمملكة العربية السعودية أثناء استخدامه لتطبيقنا وموقعنا الإلكتروني. 3 - يلتزم العميل بكافة شروطنا وأحكامنا ويجب ألا يقوم العميل بإنتهاك أي من حقوقنا لأن أي مستخدم يقوم بفعل ذلك فأننا سنقوم على الفور بحظره من استخدام تطبيقنا مع إتخاذ الإجراءات القانونية المناسبة لمعاقبته على ما قام بفعله. 4 - يمكن للعميل متابعة عروضنا الحصرية وأخر أخبارنا على صفحات التواصل الاجتماعي المختلفة الموجودين عليها. 5 - يلتزم العميل بتزويد تطبيق الناقل الافضل للغاز ببيانات صحيحة ودقيقة حتى يتمكن من إنشاء حساب جديد خاص به وحتى يتمكن العميل من استخدام تطبيقنا والتعامل معه. 6 - يقر العميل بأنه قرأ كافة الشروط والأحكام المذكورة في هذه الاتفاقية, كما يلتزم العميل بأن يقر بأن سيوافق على كافة الشروط والأحكام التي من المحتمل أن تضيفها إدارة التطبيق إلى هذه الاتفاقية بالمستقبل",
//       "termLabel8":"حدود مسؤوليتنا ",
//       "termContent8":"يقوم العميل بتسجيل حساب بالتطبيق حتى يتمكن من الشراء من المنتجات المتنوعة بالتطبيق فحدود مسؤوليتنا متمثلة في المحافظة على حقوق العميل ويشتري العميل تلك المنتجات عبر التطبيق او من وحدات الخدمة الذاتية ومن خلال وسائل الدفع التي يوفرها التطبيق وبعد ذلك يتم استلام المنتجات التي اشتراها العميل من وحدات الخدمة و المحدد مواقعها من خلال التطبيق",
//       "termLabel9":"إخلاء المسؤولية  ",
//       "termContent9":"1 - تخلي إدارة تطبيق الناقل الافضل للغاز مسؤوليتها الكاملة وذلك في حال قيام العميل بتزويدنا ببيانات خاطئة ونتج عن ذلك أي نوع من الأضرار له مثل تزويد العميل لنا ببيانات خاطئة عن عنوانه وتم إيصال مشتريات العميل إلى هذا العنوان الخاطئ. 2 - نخلي مسؤوليتنا الكاملة وذلك في حال استخدام أو سوء استخدام العميل لموقعنا أو لتطبيقنا الإلكتروني ونتج عن ذلك ضرر مباشر أو ضرر غير مباشر لهذا العميل... 6 - العميل مسؤول بشكل كامل عن البيانات الشخصية التي يزودها لنا أو عن الآراء التي يذكرها أو عن الملفات التي يقوم بتحميلها ولا تقع أي مسؤولية على تطبيق الناقل الافضل للغاز عن هذه الأمور.",
//       "termLabel10":"سياسة الخصوصية الخاصة بتطبيق وموقع الناقل الافضل للغاز",
//       "termContent10":"تأكد أن المحافظة على خصوصية بياناتك الشخصية التي تزودنا بها هي أحد أولويتنا الرئيسية لذلك نرجو منك قراءة هذه السياسة بعناية والموافقة على ما ذكر فيها من بنود حتى تتمكن من استخدام تطبيقنا وموقعنا الإلكتروني, وتشمل هذه السياسة العديد من البنود مثل البيانات التي نحتاجها منك, كيف نحمي بياناتك الشخصية, حقوق العملاء , حقوق التطبيق وغيرها من البنود الهامة الأخرى, سياسة الخصوصية الخاصة بتطبيق وموقع الناقل الافضل للغاز تحتوي على البنود التالية:- البيانات التي يحتاجها موقع وتطبيق الناقل الافضل للغاز من العملاء -: 1 - يحتاج تطبيق الناقل الافضل للغاز بعض البيانات الهامة حين يقوم العميل بإعلان رغبته بإنشاء حساب جديد له بالتطبيق والبيانات التي نحتاجها منه في هذه الحالة تكون مثل الاسم الأول واسم العائلة والبريد الإلكتروني, رقم الهاتف, الاسم بالكامل وإدخال كلمة مرور للحفاظ على حسابك الشخصي, والموافقة على سياسة الخصوصية والشروط والأحكام الخاصة بتطبيق الناقل الافضل للغاز وأي بيانات أخرى يطلبها موقع الناقل الافضل للغاز يكون العميل ملزم بشكل كامل بتزويدنا بتلك البيانات. 2 - يطلب تطبيق الناقل الافضل للغاز بعض البيانات الهامة والضرورية لاكمال عملية الدفع وذلك حين يقوم العميل بالشراء من المنتجات المتنوعة الموجودة بتطبيقنا, والبيانات التي نحتاجها في هذه الحالة تكون مثل رقم البطاقة البنكية التي يرغب العميل بالدفع من خلالها, تاريخ إنتهاء هذه البطاقة, رمز التحقق الخاص بهذه البطاقة, وأي بيانات أخرى يطلبها تطبيق الناقل الافضل للغاز لاكمال عملية الدفع يكون العميل ملزم بشكل كامل بتزويدنا بتلك البيانات. 4 - يحتاج تطبيق الناقل الافضل للغاز بعض البيانات الهامة حين يقوم العميل بإعلان رغبته بالتواصل معنا حتى نجيب له عن أي شيء مبهم بالنسبة له. 5- يطلب تطبيق الناقل الافضل للغاز بعض البيانات من العميل حول مكان المنزل حتى يظهر له أقرب أماكن المكينات المتاحة حتى نزود العميل بالمنتجات التي يحتاجها من تطبيقنا. 6 - يطلب تطبيق الناقل الافضل للغاز من العميل الموافقة على حصول التطبيق على موقعه )أي المكان الذي يعيش فيه( كما نطلب بعض البيانات حول عنوان إقامة العميل",
//       "termLabel11":" الحقوق الفكرية وحقوق النشر لتطبيق الناقل الافضل للغاز",
//       "termContent11":"قمنا بإنشاء علامة تجارية مميزة تعرف العملاء بالخدمات العظيمة التي نقدمها لهم لذلك يمنع بشكل كامل أن تقوم أي جهة أو أي فرد باستخدام علامتنا التجارية إلا بعد الحصول على موافقة مكتوبة وموقعة من قبل إدارة موقع وتطبيق الناقل الافضل للغاز حتى يتمكنوا من استخدام علامتنا التجارية. 2 - يحتوي موقع الناقل الافضل للغاز على العديد من أنواع المحتوى المملوكة بشكل كامل لإدارة التطبيق لذلك يمنع بشكل تام أن يقوم أي تطبيق أو أي موقع أو أي جهة مهما كان سلطتها نسخ أو لصق أو استخدام أي محتوى خاص بنا, لأن أي شخص أو جهة يقوم بفعل ذلك سوف يتخذ الفريق القانوني الخاص بنا إجراءات قانونية عاجلة ضد من انتهك أي من حقوقنا. 3 - يمنع أن تقوم أي جهة أو أي شخص بوضع أو تحميل أو نشر أي فيروسات أو روابط ضارة بتطبيقنا أو بموقعنا الإلكتروني وأي شخص أو جهة يقوم بفعل أي شيء من تلك الأمور فأننا سنتخذ إجراءات قانونية عاجلة ضد من قام بفعل أي شيء من تلك الأمور المحظور فعلها بتطبيقنا وموقعنا الإلكتروني. 4 - أثناء استخدامك لتطبيقنا فأنك تتعهد باستخدام تطبيقنا بشكل عادل لا يسبب لنا أية أضرار, كما يجب أن تتعهد بأنك لن تقوم بإنتهاك حقوقنا أو بمحاولة إنتهاك أي من حقوقنا لأنه من يفعل أي شيء من هذه الأمور فإن إدارة موقع وتطبيق الناقل الافضل للغاز ستتخذ إجراءات قانونية عاجلة لمعاقبة من فعل ذلك"
      
//     },
//     "en": {
//       "termLabel":"Date of agreement ",
//       "termContent":"The last update to our agreement was on 29/4/2023 .",
//       "termLabel1":"Terms and conditions for the Best Gas Carrier application.",
//       "termContent1":"The Best Gas Carrier application management has set these terms and conditions to inform customers of what they must do when they use our electronic application, because violating our terms and conditions or any of them may cause the ban or suspension of the violating customer's account.",
//       "termLabel2":"The introduction",
//       "termConent2":"We kindly ask customers to know that they must agree to our current terms or conditions that we have the right to add in the future, because if a customer does not agree to our terms or conditions or any of them, then in this case he will not be entitled to use our application or deal with it, but he must immediately exit from our application and not to use it until he agrees to all our terms and conditions",
//       "termLabel3":"Conditions for registering with the Best Gas Carrier application.",
//       "termConent3":"1 - All customers are obligated to provide us with all the data we need from them (full name, e-mail, phone number, and username) and this data must be true and accurate so that the customer can use our application and the customer must review his personal data before providing us with this data. 2 - The age of the customer wishing to register with our application must be at least 18 years old in order to be able to use our application, deal with it, and purchase from it, and those under 18 years old can use our application, if their parents agree to deal with us.3 - The customer is obligated to allow the best gas carrier application to know his location, that is, the place he lives, so that we can provide our service to him. 4 - The customer is obligated to provide us with an activated payment method so that he can deal with the application and purchase from the various products in it",
//       "termLabel4":"Conditions for dealing with the application of the best gas carrier",
//       "termContent4":"All customers are obligated to use our application in a manner that is consistent with the laws and that our electronic application does not cause any damage, and all customers must be committed to the necessity of using our application in a manner that is consistent with Islamic law. 2 - The customer, when using our application, is obligated not to do any abuse of our application, do any abuse to any other user, or do any abuse to the service supplier, because whoever does any abuse or commits any violation of any of our rights, we will ban this user from using our application with our entitlement To take all legal measures to punish those who committed this offense or committed this violation.4 - Our application has the right to accept or reject any purchase request for any customer without the need to give any reasons for their doing so. 5 - It is completely forbidden to use the Better Gas Carrier application for any commercial or advertising purposes without obtaining prior approval from the site and application management. 6 - Dealing with our application is the responsibility of the customer alone, so that the customer uses our application in a way that does not cause him any damage. 7 - The customer is obligated to pay compensation to the Best Gas Carrier application in the event that it violates its terms, or if the customer causes damage to an application while using it, or if it violates any law, and this causes the Best Gas Carrier application to pay those compensations",
//       "termLabel5":"inquiries",
//       "termContent5":"1 - Our staff is fully prepared to answer any question or inquiry you may ask them, and our staff is ready to help you understand anything ambiguous for you. 2 - If you encounter any problem while using our electronic application, you should immediately contact our technical support so that they solve your problem with your full commitment to the friendly solutions they provide you.",
//       "termLabel6":"Modifications, changes, additions and updates that may be made to this Agreement.",
//       "termContent6":"We seek to continuously develop the application of the best gas carrier in order to meet all the aspirations of customers, so the application management requests that the customers need to follow this policy constantly to get acquainted with any amendments, changes, additions or improvements that we have implemented to this agreement, because as soon as we implement any new item or We have amended any clause in this agreement, as it will be applied to all customers",
//       "termLabel7":"General conditions for the application of the Best Gas Carrier.",
//       "termContent7":"1 - The customer is obligated to use our application in a legal manner that does not cause us any damages of any kind or make us pay any compensation for any reason. 2 - Customers are obligated not to do anything that violates the laws or violates the regulations, laws and rules of the Kingdom of Saudi Arabia while using our application and our website. 3 - The customer is committed to all our terms and conditions, and the customer must not violate any of our rights, because any user who does so, we will immediately ban him from using our application, while taking appropriate legal measures to punish him for what he has done. 4 - The customer can follow our exclusive offers and our latest news on the various social networking pages they are on.5 - The customer is obligated to provide the Better Gas Carrier application with correct and accurate data so that he can create a new account for himself and so that the customer can use our application and deal with it. 6 - The customer acknowledges that he has read all the terms and conditions mentioned in this agreement, and the customer is obligated to acknowledge that he will agree to all the terms and conditions that the application management may add to this agreement in the future",
//       "termLabel8":"Limits of our responsibility  ",
//       "termContent8":"The customer registers an account in the application so that he can purchase from the various products in the application. The limits of our responsibility are represented in preserving the rights of the customer, and the customer purchases these products through the application or from the self-service units and through the payment methods provided by the application, and after that the products that the customer purchased are received from the service units Their locations are specified through the application",
//       "termLabel9":"Evacuation responsibilaty",
//       "termContent9": "1 - The management of the Better Gas Carrier application disclaims its full responsibility in the event that the customer provides us with wrong data, and this results in any kind of damage to him, such as the customer providing us with wrong data about his address, and the customer’s purchases were delivered to this wrong address. 2 - We disclaim our full responsibility in the event that the customer uses or misuses our website or our electronic application, which results in direct or indirect harm to this customer ... 6 - The customer is fully responsible for the personal data that he provides to us or for the opinions he mentions or for The files that he uploads and there is no responsibility on the application of the best gas carrier for these matters.",
//       "termLabel10":"Privacy policy for the application and site of the best gas carrier",
//       "termContent10":"Make sure that maintaining the privacy of your personal data that you provide us with is one of our main priorities. Therefore, we ask you to read this policy carefully and agree to the terms mentioned in it in order to be able to use our application and our website. This policy includes many items such as the data we need from you, how we protect Your personal data, customer rights, application rights and other important items. The privacy policy for the Best Gas Carrier application and site contains the following items: - The data that the Best Gas Carrier website and application needs from customers:1 - The Best Gas Carrier application needs some important data when the customer announces his desire to create a new account for him in the application, and the data that we need from him in this case is such as the first name, last name, email, phone number, full name, entering a password to maintain your personal account, and approval On the privacy policy, terms and conditions for the Best Gas Carrier application, and any other data requested by the Best Gas Carrier website, the customer is fully obligated to provide us with that data.2 - The Best Gas Carrier application requests some important and necessary data to complete the payment process, when the customer purchases from the various products in our application, and the data that we need in this case is such as the bank card number that the customer wishes to pay through, the expiration date of this card, the verification code For this card, and any other data required by the Better Gas Carrier application to complete the payment process, the customer is fully obligated to provide us with that data. 4 - The application of the best gas carrier needs some important data when the customer announces his desire to communicate with us so that we can answer him about anything vague to him.5- The Better Gas Carrier application requests some data from the customer about the location of the house in order to show him the nearest available machinery locations so that we provide the customer with the products he needs from our application. 6 - The best gas carrier application asks the customer to agree to the application obtaining his location (i.e. the place where he lives) and we also require some data about the customer’s residence address",
//       "termLabel11":"Intellectual rights and copyrights for the application of the best gas carrier",
//       "termContent11":" We have created a distinctive brand that defines customers with the great services that we offer them. Therefore, it is completely forbidden for any party or individual to use our trademark except after obtaining a written and signed approval from the management of the Better Gas Carrier website and application so that they can use our trademark. 2 - The Best Gas Carrier website contains many types of content that are wholly owned by the management of the application, so it is strictly forbidden for any application, any site, or any party, regardless of its authority, to copy, paste, or use any of our content, because any person or party By doing so, our legal team will take urgent legal action against those who have violated any of our rights.3 - It is forbidden for any party or person to put, upload or publish any viruses or harmful links to our application or our website, and any person or entity that does any of these matters, we will take urgent legal measures against whoever does any of these prohibited things Do it with our app and website. 4 - While using our application, you undertake to use our application in a fair manner that does not cause us any damage, and you must also undertake that you will not violate our rights or attempt to violate any of our rights because whoever does any of these matters, the management of the site and application of the best gas carrier will take legal measures Urgent to punish whoever did it "
      
//     }
// };  


var arrLang = {
  "ar": {
    "title":"الشروط والأحكام",
    "termLabel":"تاريخ الاتفاقية",
    "termContent":"آخر تحديث تم القيام به للإتفاقية الخاصة بنا كان بتاريخ 29/04/2023م.",
    "termLabel1":"الشروط والأحكام الخاصة بتطبيق الناقل الأفضل للغاز  ",
    "termContent1":"قامت إدارة تطبيق الناقل الافضل للغاز بوضع هذه الشروط والأحكام لتعريف العملاء بما يجب عليهم القيام به عند استخدامهم لتطبيقنا الإليكتروني, لأن مخالفة شروطنا وأحكامنا أو أحدًا منها من الممكن أن يتسبب ذلك في حظر أو إيقاف حساب العميل المخالف.",
    "termLabel2":"المقدمة",
    "termContent2":"نرجو من السادة العملاء العلم بأنه يجب عليهم الموافقة على شروطنا الحالية أو الشروط التي يحق لنا إضافتها بالمستقبل ألنه في حالة عدم موافقة أحد العملاء على شروطنا أو أحكامنا أو أحدًا منهم ففي هذه الحالة لن يحق له استخدام تطبيقنا أو التعامل معه بل يجب عليه على الفور الخروج من تطبيقنا وألا يقوم باستخدامه حتى يوافق على كافة شروطنا وأحكامنا    </div>",
    "termLabel3":" شروط التسجيل بتطبيق الناقل الافضل للغاز",
    "termContent3":"1 -يلتزم كافة العملاء بتزويدنا بكافة البيانات التي نحتاجها منهم (الإسم بالكامل والبريد الإليكتروني, رقم الهاتف, واسم المستخدم)كما يجب أن تكون هذه البيانات صحيحة ودقيقة حتى يتمكن العميل من استخدام تطبيقنا كما يجب على العميل مراجعة بياناته الشخصية قبل تزويدنا بهذه البيانات. 2 -يجب أن يكون عمر العميل الراغب بالتسجيل بتطبيقنا هو 18 عام على الأقل حتى يتمكن من استخدام تطبيقنا والتعامل معه والشراء منه, كما يمكن لمن هم دون 18 عام استخدام تطبيقنا وذلك في حال موافقة والديهم على قيامهم بالتعامل معنا. 3 -يلتزم العميل بالسماح لتطبيق الناقل الافضل للغاز بمعرفة موقعه أي المكان الذي يعيش حتى نتمكن من تقديم خدمتنا إليه. 4 -يلتزم العميل بتزويدنا بوسيلة دفع مفعلة حتى يتمكن من التعامل مع التطبيق والشراء من المنتجات المتنوعة الموجودة فيه",
    "termLabel4":"شروط التعامل مع تطبيق الناقل الافضل للغاز",
    "termContent4":"يلتزم كافة العملاء بضرورة استخدام تطبيقنا بشكل يتوافق مع القوانين ولا يسبب لتطبيقنا الإلكتروني أية أضرار,كما يجب أن يلتزم كافة العملاء بضرورة استخدام تطبيقنا بشكل يتوافق مع الشريعة الإسلامية. 2 - يلتزم العميل عند استخدامه لتطبيقنا بألا يقوم بفعل أي إساءة لتطبيقنا أو فعل أي إساءة لأي مستخدم آخر أو فعل أي إساءة لمورد الخدمة لأن من يقوم بفعل إي إساءة أو يقوم بفعل أي انتهاك أي من حقوقنا فأننا سنقوم بحظر هذا المستخدم من استخدام تطبيقنا مع إحقيتنا في إتخاذ كافة الإجراءات القانونية لمعاقبة من قام بفعل هذه الإساءة أو قام بفعل هذا الانتهاك.. 4 - يحق لتطبيقنا قبول أو رفض أي طلب شراء خاص بأي عميل دون الحاجة إلى إبداء أية أسباب لقيامهم بفعل ذلك. 5 - يمنع بشكل كامل أن يتم استخدام تطبيق الناقل الافضل للغاز لأية أغراض تجارية أو أية أغراض إعلانية دون الحصول على موافقة مسبقة من قبل إدارة الموقع والتطبيق. 6 - التعامل مع تطبيقنا يكون واقع على مسؤولية العميل وحده بحيث يستخدم العميل تطبيقنا بشكل لا يسبب له أية أضرار. 7 - يلتزم العميل بتحمل دفع تعويضات لتطبيق الناقل الافضل للغاز في حالة مخالفته لشروطه أو في حال تسبب العميل بضرر لتطبيق أثناء استخدامه له أو في حال انتهاكه لأي قانون وتسبب ذلك في جعل تطبيق الناقل الافضل للغاز يدفع تلك التعويضات",
    "termLabel5":"الاستفسارات",
    "termContent5":"1 - موظفينا على أتم الاستعداد للإجابة على أي سؤال أو استفسار تطرحه عليهم, كما أن موظفينا مستعدين لمساعدتك في فهم أي شيء غامض بالنسبة لك. 2 - إذا واجهت أي مشكلة أثناء استخدامك لتطبيقنا الإلكتروني فعليك على الفور التواصل مع الدعم الفني الخاص بنا حتى يقوموا بحل مشكلتك مع إلتزامك بشكل كامل بالحلول الودية التي يقدمونها لك",
    "termLabel6":"التعديلات والتغييرات والإضافات والتحديثات التي يمكن إجراؤها لهذه الاتفاقية",
    "termContent6":"نسعى إلى تطوير تطبيق الناقل الافضل للغاز بشكل مستمر حتى يلبي كافة تطلعات العملاء, لذلك ترجو إدارة التطبيق من السادة العملاء ضرورة متابعة هذه السياسة باستمرار للتعرف على أي تعديلات أو تغييرات أو إضافات أو تحسينات قمنا بتنفيذها لهذه الاتفاقية, لأنه بمجرد قيامنا بتنفيذ أي بند جديد أو قمنا بتعديل أي بند موجود في هذه الاتفاقية فأنه سيكون مطبق على كافة العملاء ",
    "termLabel7":"شروط عامة خاصة بتطبيق الناقل الافضل للغاز",
    "termContent7":"1 - يلتزم العميل باستخدام تطبيقنا بشكل قانوني لا يسبب لنا أية أضرار من أي نوع أو يجعلنا نقوم بدفع أية تعويضات لأي سبب كان. 2 - يلتزم العملاء بعدم فعل أي شيء ينتهك القوانين أو ينتهك الأنظمة والقوانين والقواعد الخاصة بالمملكة العربية السعودية أثناء استخدامه لتطبيقنا وموقعنا الإلكتروني. 3 - يلتزم العميل بكافة شروطنا وأحكامنا ويجب ألا يقوم العميل بإنتهاك أي من حقوقنا لأن أي مستخدم يقوم بفعل ذلك فأننا سنقوم على الفور بحظره من استخدام تطبيقنا مع إتخاذ الإجراءات القانونية المناسبة لمعاقبته على ما قام بفعله. 4 - يمكن للعميل متابعة عروضنا الحصرية وأخر أخبارنا على صفحات التواصل الاجتماعي المختلفة الموجودين عليها. 5 - يلتزم العميل بتزويد تطبيق الناقل الافضل للغاز ببيانات صحيحة ودقيقة حتى يتمكن من إنشاء حساب جديد خاص به وحتى يتمكن العميل من استخدام تطبيقنا والتعامل معه. 6 - يقر العميل بأنه قرأ كافة الشروط والأحكام المذكورة في هذه الاتفاقية, كما يلتزم العميل بأن يقر بأن سيوافق على كافة الشروط والأحكام التي من المحتمل أن تضيفها إدارة التطبيق إلى هذه الاتفاقية بالمستقبل",
    "termLabel8":"حدود مسؤوليتنا ",
    "termContent8":"يقوم العميل بتسجيل حساب بالتطبيق حتى يتمكن من الشراء من المنتجات المتنوعة بالتطبيق فحدود مسؤوليتنا متمثلة في المحافظة على حقوق العميل ويشتري العميل تلك المنتجات عبر التطبيق او من وحدات الخدمة الذاتية ومن خلال وسائل الدفع التي يوفرها التطبيق وبعد ذلك يتم استلام المنتجات التي اشتراها العميل من وحدات الخدمة و المحدد مواقعها من خلال التطبيق",
    "termLabel9":"إخلاء المسؤولية  ",
    "termContent9":"1 - تخلي إدارة تطبيق الناقل الافضل للغاز مسؤوليتها الكاملة وذلك في حال قيام العميل بتزويدنا ببيانات خاطئة ونتج عن ذلك أي نوع من الأضرار له مثل تزويد العميل لنا ببيانات خاطئة عن عنوانه وتم إيصال مشتريات العميل إلى هذا العنوان الخاطئ. 2 - نخلي مسؤوليتنا الكاملة وذلك في حال استخدام أو سوء استخدام العميل لموقعنا أو لتطبيقنا الإلكتروني ونتج عن ذلك ضرر مباشر أو ضرر غير مباشر لهذا العميل... 6 - العميل مسؤول بشكل كامل عن البيانات الشخصية التي يزودها لنا أو عن الآراء التي يذكرها أو عن الملفات التي يقوم بتحميلها ولا تقع أي مسؤولية على تطبيق الناقل الافضل للغاز عن هذه الأمور.",
    "termLabel10":"سياسة الخصوصية الخاصة بتطبيق وموقع الناقل الافضل للغاز",
    "termContent10":"تأكد أن المحافظة على خصوصية بياناتك الشخصية التي تزودنا بها هي أحد أولويتنا الرئيسية لذلك نرجو منك قراءة هذه السياسة بعناية والموافقة على ما ذكر فيها من بنود حتى تتمكن من استخدام تطبيقنا وموقعنا الإلكتروني, وتشمل هذه السياسة العديد من البنود مثل البيانات التي نحتاجها منك, كيف نحمي بياناتك الشخصية, حقوق العملاء , حقوق التطبيق وغيرها من البنود الهامة الأخرى, سياسة الخصوصية الخاصة بتطبيق وموقع الناقل الافضل للغاز تحتوي على البنود التالية:- البيانات التي يحتاجها موقع وتطبيق الناقل الافضل للغاز من العملاء -: 1 - يحتاج تطبيق الناقل الافضل للغاز بعض البيانات الهامة حين يقوم العميل بإعلان رغبته بإنشاء حساب جديد له بالتطبيق والبيانات التي نحتاجها منه في هذه الحالة تكون مثل الاسم الأول واسم العائلة والبريد الإلكتروني, رقم الهاتف, الاسم بالكامل وإدخال كلمة مرور للحفاظ على حسابك الشخصي, والموافقة على سياسة الخصوصية والشروط والأحكام الخاصة بتطبيق الناقل الافضل للغاز وأي بيانات أخرى يطلبها موقع الناقل الافضل للغاز يكون العميل ملزم بشكل كامل بتزويدنا بتلك البيانات. 2 - يطلب تطبيق الناقل الافضل للغاز بعض البيانات الهامة والضرورية لاكمال عملية الدفع وذلك حين يقوم العميل بالشراء من المنتجات المتنوعة الموجودة بتطبيقنا, والبيانات التي نحتاجها في هذه الحالة تكون مثل رقم البطاقة البنكية التي يرغب العميل بالدفع من خلالها, تاريخ إنتهاء هذه البطاقة, رمز التحقق الخاص بهذه البطاقة, وأي بيانات أخرى يطلبها تطبيق الناقل الافضل للغاز لاكمال عملية الدفع يكون العميل ملزم بشكل كامل بتزويدنا بتلك البيانات. 4 - يحتاج تطبيق الناقل الافضل للغاز بعض البيانات الهامة حين يقوم العميل بإعلان رغبته بالتواصل معنا حتى نجيب له عن أي شيء مبهم بالنسبة له. 5- يطلب تطبيق الناقل الافضل للغاز بعض البيانات من العميل حول مكان المنزل حتى يظهر له أقرب أماكن المكينات المتاحة حتى نزود العميل بالمنتجات التي يحتاجها من تطبيقنا. 6 - يطلب تطبيق الناقل الافضل للغاز من العميل الموافقة على حصول التطبيق على موقعه )أي المكان الذي يعيش فيه( كما نطلب بعض البيانات حول عنوان إقامة العميل",
    "termLabel11":" الحقوق الفكرية وحقوق النشر لتطبيق الناقل الافضل للغاز",
    "termContent11":"قمنا بإنشاء علامة تجارية مميزة تعرف العملاء بالخدمات العظيمة التي نقدمها لهم لذلك يمنع بشكل كامل أن تقوم أي جهة أو أي فرد باستخدام علامتنا التجارية إلا بعد الحصول على موافقة مكتوبة وموقعة من قبل إدارة موقع وتطبيق الناقل الافضل للغاز حتى يتمكنوا من استخدام علامتنا التجارية. 2 - يحتوي موقع الناقل الافضل للغاز على العديد من أنواع المحتوى المملوكة بشكل كامل لإدارة التطبيق لذلك يمنع بشكل تام أن يقوم أي تطبيق أو أي موقع أو أي جهة مهما كان سلطتها نسخ أو لصق أو استخدام أي محتوى خاص بنا, لأن أي شخص أو جهة يقوم بفعل ذلك سوف يتخذ الفريق القانوني الخاص بنا إجراءات قانونية عاجلة ضد من انتهك أي من حقوقنا. 3 - يمنع أن تقوم أي جهة أو أي شخص بوضع أو تحميل أو نشر أي فيروسات أو روابط ضارة بتطبيقنا أو بموقعنا الإلكتروني وأي شخص أو جهة يقوم بفعل أي شيء من تلك الأمور فأننا سنتخذ إجراءات قانونية عاجلة ضد من قام بفعل أي شيء من تلك الأمور المحظور فعلها بتطبيقنا وموقعنا الإلكتروني. 4 - أثناء استخدامك لتطبيقنا فأنك تتعهد باستخدام تطبيقنا بشكل عادل لا يسبب لنا أية أضرار, كما يجب أن تتعهد بأنك لن تقوم بإنتهاك حقوقنا أو بمحاولة إنتهاك أي من حقوقنا لأنه من يفعل أي شيء من هذه الأمور فإن إدارة موقع وتطبيق الناقل الافضل للغاز ستتخذ إجراءات قانونية عاجلة لمعاقبة من فعل ذلك"
  },
  "en": {
    "title":"Terms and Conditions",
    "termLabel":"Date of agreement ",
    "termContent":"The last update to our agreement was on 29/4/2023 .",
    "termLabel1":"Terms and conditions for the Best Gas Carrier application.",
    "termContent1":"The Best Gas Carrier application management has set these terms and conditions to inform customers of what they must do when they use our electronic application, because violating our terms and conditions or any of them may cause the ban or suspension of the violating customer's account.",
    "termLabel2":"The introduction",
    "termContent2":"We kindly ask customers to know that they must agree to our current terms or conditions that we have the right to add in the future, because if a customer does not agree to our terms or conditions or any of them, then in this case he will not be entitled to use our application or deal with it, but he must immediately exit from our application and not to use it until he agrees to all our terms and conditions",
    "termLabel3":"Conditions for registering with the Best Gas Carrier application.",
    "termContent3":"1 - All customers are obligated to provide us with all the data we need from them (full name, e-mail, phone number, and username) and this data must be true and accurate so that the customer can use our application and the customer must review his personal data before providing us with this data. 2 - The age of the customer wishing to register with our application must be at least 18 years old in order to be able to use our application, deal with it, and purchase from it, and those under 18 years old can use our application, if their parents agree to deal with us.3 - The customer is obligated to allow the best gas carrier application to know his location, that is, the place he lives, so that we can provide our service to him. 4 - The customer is obligated to provide us with an activated payment method so that he can deal with the application and purchase from the various products in it",
    "termLabel4":"Conditions for dealing with the application of the best gas carrier",
    "termContent4":"All customers are obligated to use our application in a manner that is consistent with the laws and that our electronic application does not cause any damage, and all customers must be committed to the necessity of using our application in a manner that is consistent with Islamic law. 2 - The customer, when using our application, is obligated not to do any abuse of our application, do any abuse to any other user, or do any abuse to the service supplier, because whoever does any abuse or commits any violation of any of our rights, we will ban this user from using our application with our entitlement To take all legal measures to punish those who committed this offense or committed this violation.4 - Our application has the right to accept or reject any purchase request for any customer without the need to give any reasons for their doing so. 5 - It is completely forbidden to use the Better Gas Carrier application for any commercial or advertising purposes without obtaining prior approval from the site and application management. 6 - Dealing with our application is the responsibility of the customer alone, so that the customer uses our application in a way that does not cause him any damage. 7 - The customer is obligated to pay compensation to the Best Gas Carrier application in the event that it violates its terms, or if the customer causes damage to an application while using it, or if it violates any law, and this causes the Best Gas Carrier application to pay those compensations",
    "termLabel5":"inquiries",
    "termContent5":"1 - Our staff is fully prepared to answer any question or inquiry you may ask them, and our staff is ready to help you understand anything ambiguous for you. 2 - If you encounter any problem while using our electronic application, you should immediately contact our technical support so that they solve your problem with your full commitment to the friendly solutions they provide you.",
    "termLabel6":"Modifications, changes, additions and updates that may be made to this Agreement.",
    "termContent6":"We seek to continuously develop the application of the best gas carrier in order to meet all the aspirations of customers, so the application management requests that the customers need to follow this policy constantly to get acquainted with any amendments, changes, additions or improvements that we have implemented to this agreement, because as soon as we implement any new item or We have amended any clause in this agreement, as it will be applied to all customers",
    "termLabel7":"General conditions for the application of the Best Gas Carrier.",
    "termContent7":"1 - The customer is obligated to use our application in a legal manner that does not cause us any damages of any kind or make us pay any compensation for any reason. 2 - Customers are obligated not to do anything that violates the laws or violates the regulations, laws and rules of the Kingdom of Saudi Arabia while using our application and our website. 3 - The customer is committed to all our terms and conditions, and the customer must not violate any of our rights, because any user who does so, we will immediately ban him from using our application, while taking appropriate legal measures to punish him for what he has done. 4 - The customer can follow our exclusive offers and our latest news on the various social networking pages they are on.5 - The customer is obligated to provide the Better Gas Carrier application with correct and accurate data so that he can create a new account for himself and so that the customer can use our application and deal with it. 6 - The customer acknowledges that he has read all the terms and conditions mentioned in this agreement, and the customer is obligated to acknowledge that he will agree to all the terms and conditions that the application management may add to this agreement in the future",
    "termLabel8":"Limits of our responsibility  ",
    "termContent8":"The customer registers an account in the application so that he can purchase from the various products in the application. The limits of our responsibility are represented in preserving the rights of the customer, and the customer purchases these products through the application or from the self-service units and through the payment methods provided by the application, and after that the products that the customer purchased are received from the service units Their locations are specified through the application",
    "termLabel9":"Evacuation responsibilaty",
    "termContent9": "1 - The management of the Better Gas Carrier application disclaims its full responsibility in the event that the customer provides us with wrong data, and this results in any kind of damage to him, such as the customer providing us with wrong data about his address, and the customer’s purchases were delivered to this wrong address. 2 - We disclaim our full responsibility in the event that the customer uses or misuses our website or our electronic application, which results in direct or indirect harm to this customer ... 6 - The customer is fully responsible for the personal data that he provides to us or for the opinions he mentions or for The files that he uploads and there is no responsibility on the application of the best gas carrier for these matters.",
    "termLabel10":"Privacy policy for the application and site of the best gas carrier",
    "termContent10":"Make sure that maintaining the privacy of your personal data that you provide us with is one of our main priorities. Therefore, we ask you to read this policy carefully and agree to the terms mentioned in it in order to be able to use our application and our website. This policy includes many items such as the data we need from you, how we protect Your personal data, customer rights, application rights and other important items. The privacy policy for the Best Gas Carrier application and site contains the following items: - The data that the Best Gas Carrier website and application needs from customers:1 - The Best Gas Carrier application needs some important data when the customer announces his desire to create a new account for him in the application, and the data that we need from him in this case is such as the first name, last name, email, phone number, full name, entering a password to maintain your personal account, and approval On the privacy policy, terms and conditions for the Best Gas Carrier application, and any other data requested by the Best Gas Carrier website, the customer is fully obligated to provide us with that data.2 - The Best Gas Carrier application requests some important and necessary data to complete the payment process, when the customer purchases from the various products in our application, and the data that we need in this case is such as the bank card number that the customer wishes to pay through, the expiration date of this card, the verification code For this card, and any other data required by the Better Gas Carrier application to complete the payment process, the customer is fully obligated to provide us with that data. 4 - The application of the best gas carrier needs some important data when the customer announces his desire to communicate with us so that we can answer him about anything vague to him.5- The Better Gas Carrier application requests some data from the customer about the location of the house in order to show him the nearest available machinery locations so that we provide the customer with the products he needs from our application. 6 - The best gas carrier application asks the customer to agree to the application obtaining his location (i.e. the place where he lives) and we also require some data about the customer’s residence address",
    "termLabel11":"Intellectual rights and copyrights for the application of the best gas carrier",
    "termContent11":" We have created a distinctive brand that defines customers with the great services that we offer them. Therefore, it is completely forbidden for any party or individual to use our trademark except after obtaining a written and signed approval from the management of the Better Gas Carrier website and application so that they can use our trademark. 2 - The Best Gas Carrier website contains many types of content that are wholly owned by the management of the application, so it is strictly forbidden for any application, any site, or any party, regardless of its authority, to copy, paste, or use any of our content, because any person or party By doing so, our legal team will take urgent legal action against those who have violated any of our rights.3 - It is forbidden for any party or person to put, upload or publish any viruses or harmful links to our application or our website, and any person or entity that does any of these matters, we will take urgent legal measures against whoever does any of these prohibited things Do it with our app and website. 4 - While using our application, you undertake to use our application in a fair manner that does not cause us any damage, and you must also undertake that you will not violate our rights or attempt to violate any of our rights because whoever does any of these matters, the management of the site and application of the best gas carrier will take legal measures Urgent to punish whoever did it "
  }
 
};


$(document).ready(function() {
  // The default language is English
  var lang = "ar";
  $(".lang").each(function(index, element) {
    $(this).text(arrLang[lang][$(this).attr("key")]);
  });
});

// get/set the selected language

  $("#select").change(function() {
  // var lang = $(this).attr("id");
  var lang= $("#select option:selected").val()


  var dir = $("html").attr("dir");
  if(dir == "rtl")
  {
     $("html").attr("dir", "ltr");
  }else{
         $("html").attr("dir", "rtl");

  }
  $(".lang").each(function(index, element) {
    $(this).text(arrLang[lang][$(this).attr("key")]);
  });

});

